# Generated by Django 6.0.6 on 2026-07-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Harvested', 'Harvested'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Distributor', 'Distributor'), ('Retailer', 'Retailer'), ('Delivered', 'Delivered')], max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='products.product')),
            ],
        ),
    ]
