# Generated by Django 6.0.6 on 2026-07-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('Harvested', 'Harvested'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Retailer Received', 'Retailer Received'), ('Delivered', 'Delivered')], max_length=30),
        ),
    ]
